### PR TITLE
site and post license

### PR DESCRIPTION
**Pull request by guoyunhe**
By default, each post is "No License".

If all posts in site have the same license, specify license code in _config.yml:

```
license: CC-BY-SA-3.0
```

You can specify license code in the header:

```
---
license: CC-BY-SA-3.0
---
```

image

### CODE REVIEW

**Comment by hellcp** [comment]
I would say it should be "Copyright", but yeah, this looks very nice

**Comment by guoyunhe** [comment]
Common copyright form is like:

> Copyright © 2002 John Doe

In RPM spec files, the license name filed is called `License:`. So I think `license` is more clear for usage.

**Comment by hellcp** [comment]
I meant instead of "No license"

**Comment by vinzv** [comment]
You can't waive copyright proactively in Germany. Assuming that lots of the content on news.o.o is produced by SUSE employees we have to state "License: <whatever license>".

**Pull request merged**
